groups:
  - name: node-basics
    rules:
      - alert: InstanceDown
        expr: up{job=~"node_exporter_.*|node_exporter_nodes|prometheus"} == 0
        for: 2m
        labels: { severity: critical }
        annotations:
          summary: "Instance down: {{ $labels.instance }}"
          description: "No scrape data for 2 minutes."

      - alert: HighCPUUsage
        expr: 100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m]))) > 90
        for: 5m
        labels: { severity: warning }
        annotations:
          summary: "High CPU on {{ $labels.instance }}"
          description: "CPU usage > 90% for 5m."

      - alert: LowMemoryAvailable
        expr: 100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 90
        for: 5m
        labels: { severity: warning }
        annotations:
          summary: "Low memory on {{ $labels.instance }}"
          description: "Available memory < 10% for 5m."

      - alert: DiskSpaceLow
        expr: 100 * (1 - (node_filesystem_avail_bytes{fstype!~"tmpfs|overlay|squashfs"} / node_filesystem_size_bytes{fstype!~"tmpfs|overlay|squashfs"})) > 90
        for: 10m
        labels: { severity: critical }
        annotations:
          summary: "Low disk space on {{ $labels.instance }} ({{ $labels.mountpoint }})"
          description: "Free space <10% for 10m."
